title: my blog
author: Gr
email: 15882264545@163.com
description: > # this means to ignore newlines until "baseurl:"


# social links
twitter_username: 
github_username:  Gr814

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minimal
